"""Initial migration.

Revision ID: 525d60a51d51
Revises: 
Create Date: 2025-04-06 16:16:25.540063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525d60a51d51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('f_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.drop_column('f_name')

    # ### end Alembic commands ###
